steps:
    # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "us-central1-docker.pkg.dev/mdn-transparencia-prd/mdn-transparencia-registry-prd/ms-helios-frontend:$SHORT_SHA", "." ]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "us-central1-docker.pkg.dev/mdn-transparencia-prd/mdn-transparencia-registry-prd/ms-helios-frontend:$SHORT_SHA" ]
    # deploy container image to CLOUD RUN
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--port=80'
      - >-
        --image=us-central1-docker.pkg.dev/mdn-transparencia-prd/mdn-transparencia-registry-prd/ms-helios-frontend:$SHORT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$SHORT_SHA,gcb-build-id=$BUILD_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
substitutions:
  _DEPLOY_REGION: us-central1
  _SERVICE_NAME: ms-helios-frontend
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'