steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg=VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}"
      - "--build-arg=VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}"
      - "--build-arg=VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}"
      - "--build-arg=VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}"
      - "--build-arg=VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}"
      - "--build-arg=VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}"
      - "--build-arg=VITE_FIREBASE_MEASUREMENT_ID=${_VITE_FIREBASE_MEASUREMENT_ID}"
      - "--build-arg=VITE_API_BASE_URL=${_VITE_API_BASE_URL}"
      - "-t"
      - "us-central1-docker.pkg.dev/min-def-c2-dev/mindef-c2/ms-helios-frontend:$SHORT_SHA"
      - "."
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "us-central1-docker.pkg.dev/min-def-c2-dev/mindef-c2/ms-helios-frontend:$SHORT_SHA" ]
    # deploy container image to CLOUD RUN
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--port=80'
      - >-
        --image=us-central1-docker.pkg.dev/min-def-c2-dev/mindef-c2/ms-helios-frontend:$SHORT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$SHORT_SHA,gcb-build-id=$BUILD_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
substitutions:
  _DEPLOY_REGION: us-central1
  _SERVICE_NAME: ms-helios-frontend
  _VITE_FIREBASE_API_KEY: ""
  _VITE_FIREBASE_AUTH_DOMAIN: ""
  _VITE_FIREBASE_PROJECT_ID: ""
  _VITE_FIREBASE_STORAGE_BUCKET: ""
  _VITE_FIREBASE_MESSAGING_SENDER_ID: ""
  _VITE_FIREBASE_APP_ID: ""
  _VITE_FIREBASE_MEASUREMENT_ID: ""
  _VITE_API_BASE_URL: ""
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'