apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-helios-frontend
  namespace: helios
  labels:
    app: ms-helios-frontend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ms-helios-frontend
  template:
    metadata:
      labels:
        app: ms-helios-frontend
    spec:
      containers:
        - name: ms-helios-frontend
          image: us-central1-docker.pkg.dev/mdn-transparencia-prd/mdn-transparencia-registry-prd/ms-helios-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: ms-helios-frontend-configmap
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
